create database REGISTRY_DB;
use REGISTRY_DB;

CREATE TABLE `BINDING_TYPE` (
  `BINDING_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`BINDING_TYPE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8
;
CREATE TABLE `SERVICE_TYPE` (
  `SERVICE_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`SERVICE_TYPE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8
;
CREATE TABLE `CONTACT_INFO` (
  `CONTACT_INFO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `PERSON_NAME` varchar(100) NOT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_INFO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `INSTITUTION` (
  `INSTITUTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INSTITUTION_NAME` varchar(75) NOT NULL,
  `CONTACT_INFO_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`INSTITUTION_ID`),
  UNIQUE KEY `INSTITUTION_NAME` (`INSTITUTION_NAME`),
  UNIQUE KEY `CONTACT_INFO_ID` (`CONTACT_INFO_ID`),
  KEY `FKB57D3998F674B373` (`CONTACT_INFO_ID`),
  CONSTRAINT `FKB57D3998F674B373` FOREIGN KEY (`CONTACT_INFO_ID`) REFERENCES `CONTACT_INFO` (`CONTACT_INFO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `SERVICE` (
  `SERVICE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `SERVICE_NAME` varchar(50) NOT NULL,
  `SERVICE_TYPE_ID` bigint(20) NOT NULL,
  `INSTITUTION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  UNIQUE KEY `SERVICE_NAME` (`SERVICE_NAME`,`INSTITUTION_ID`),
  KEY `FKA10F52959317D960` (`INSTITUTION_ID`),
  KEY `FKA10F5295B0EE15AB` (`SERVICE_TYPE_ID`),
  CONSTRAINT `FKA10F5295B0EE15AB` FOREIGN KEY (`SERVICE_TYPE_ID`) REFERENCES `SERVICE_TYPE` (`SERVICE_TYPE_ID`),
  CONSTRAINT `FKA10F52959317D960` FOREIGN KEY (`INSTITUTION_ID`) REFERENCES `INSTITUTION` (`INSTITUTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `BINDING` (
  `BINDING_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `END_POINT` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `BINDING_TYPE_ID` bigint(20) NOT NULL,
  `SERVICE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`BINDING_ID`),
  KEY `FK24583A65354D3400` (`SERVICE_ID`),
  KEY `FK24583A6545F914B` (`BINDING_TYPE_ID`),
  CONSTRAINT `FK24583A6545F914B` FOREIGN KEY (`BINDING_TYPE_ID`) REFERENCES `BINDING_TYPE` (`BINDING_TYPE_ID`),
  CONSTRAINT `FK24583A65354D3400` FOREIGN KEY (`SERVICE_ID`) REFERENCES `SERVICE` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;


