CREATE database SSIM_DB
;
CREATE TABLE `AGE` (
  `AGE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`AGE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `AUDIO_QUALITY` (
  `AUDIO_QUALITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`AUDIO_QUALITY_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8
;
CREATE TABLE `COLLECTOR` (
  `COLLECTOR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`COLLECTOR_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `CORPUS` (
  `CORPUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`CORPUS_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `DOMAIN` (
  `DOMAIN_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`DOMAIN_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
;
CREATE TABLE `ENC_QUALITY` (
  `ENC_QUALITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ENC_QUALITY_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENC_REASON` (
  `ENC_REASON_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`ENC_REASON_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENCOUNTER_TYPE` (
  `ENCOUNTER_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ENCOUNTER_TYPE_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ETHNICITY` (
  `ETHNICITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`ETHNICITY_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `FILE_TYPE` (
  `FILE_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`FILE_TYPE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `GENDER` (
  `GENDER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`GENDER_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
;
CREATE TABLE `GENERAL_TIME` (
  `GENERAL_TIME_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(50) NOT NULL,
  PRIMARY KEY (`GENERAL_TIME_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `GEO_LOCATION` (
  `GEO_LOCATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`GEO_LOCATION_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `INTERVIEW_TYPE` (
  `INTERVIEW_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`INTERVIEW_TYPE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
;
CREATE TABLE `LANGUAGE` (
  `LANGUAGE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`LANGUAGE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `PARTICIPANT_TYPE` (
  `PARTICIPANT_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`PARTICIPANT_TYPE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
;
CREATE TABLE `RANK` (
  `RANK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`RANK_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ROLE` (
  `ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `SITE` (
  `SITE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`SITE_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `VIDEO_QUALITY` (
  `VIDEO_QUALITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(100) NOT NULL,
  PRIMARY KEY (`VIDEO_QUALITY_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8
;
CREATE TABLE `INTERVIEW` (
  `INTERVIEW_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COLLECTION_DATE` datetime DEFAULT NULL,
  `SYS_DATE` datetime DEFAULT NULL,
  `GEO_LOCATION_ID` bigint(20) NOT NULL,
  `INTERVIEW_TYPE_ID` bigint(20) NOT NULL,
  `SITE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`INTERVIEW_ID`),
  UNIQUE KEY `INTERVIEW_TYPE_ID` (`INTERVIEW_TYPE_ID`,`GEO_LOCATION_ID`,`SITE_ID`),
  KEY `FK_INTERVIEW_TYPE` (`INTERVIEW_TYPE_ID`),
  KEY `FK_INT_GEO_LOCATION` (`GEO_LOCATION_ID`),
  KEY `FK_INT_SITE` (`SITE_ID`),
  CONSTRAINT `FK_INT_SITE` FOREIGN KEY (`SITE_ID`) REFERENCES `SITE` (`SITE_ID`),
  CONSTRAINT `FK_INTERVIEW_TYPE` FOREIGN KEY (`INTERVIEW_TYPE_ID`) REFERENCES `INTERVIEW_TYPE` (`INTERVIEW_TYPE_ID`),
  CONSTRAINT `FK_INT_GEO_LOCATION` FOREIGN KEY (`GEO_LOCATION_ID`) REFERENCES `GEO_LOCATION` (`GEO_LOCATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ARTIFACT` (
  `ARTIFACT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COLLECTION_DATE` datetime DEFAULT NULL,
  `COMMENTS` longtext,
  `DESCRIPTION` longtext,
  `FILE_NAME` varchar(255) NOT NULL,
  `PROCESSED` binary(1) DEFAULT NULL,
  `SYS_DATE` datetime DEFAULT NULL,
  `AUDIO_QUALITY_ID` bigint(20) DEFAULT NULL,
  `COLLECTOR_ID` bigint(20) DEFAULT NULL,
  `CORPUS_ID` bigint(20) DEFAULT NULL,
  `FILE_TYPE_ID` bigint(20) NOT NULL,
  `GENERAL_TIME_ID` bigint(20) DEFAULT NULL,
  `GEO_LOCATION_ID` bigint(20) DEFAULT NULL,
  `SITE_ID` bigint(20) DEFAULT NULL,
  `VIDEO_QUALITY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ARTIFACT_ID`),
  UNIQUE KEY `FILE_NAME` (`FILE_NAME`),
  KEY `FK_A_FILE_TYPE` (`FILE_TYPE_ID`),
  KEY `FK_A_COLLECTOR` (`COLLECTOR_ID`),
  KEY `FK_A_AUDIO_QUALITY` (`AUDIO_QUALITY_ID`),
  KEY `FK_A_VIDEO_QUALITY` (`VIDEO_QUALITY_ID`),
  KEY `FK_A_GENERAL_TIME` (`GENERAL_TIME_ID`),
  KEY `FK_A_SITE` (`SITE_ID`),
  KEY `FK_A_GEO_LOCATION` (`GEO_LOCATION_ID`),
  KEY `FK_A_CORPUS` (`CORPUS_ID`),
  CONSTRAINT `FK_A_FILE_TYPE` FOREIGN KEY (`FILE_TYPE_ID`) REFERENCES `FILE_TYPE` (`FILE_TYPE_ID`),
  CONSTRAINT `FK_A_VIDEO_QUALITY` FOREIGN KEY (`VIDEO_QUALITY_ID`) REFERENCES `VIDEO_QUALITY` (`VIDEO_QUALITY_ID`),
  CONSTRAINT `FK_A_AUDIO_QUALITY` FOREIGN KEY (`AUDIO_QUALITY_ID`) REFERENCES `AUDIO_QUALITY` (`AUDIO_QUALITY_ID`),
  CONSTRAINT `FK_A_COLLECTOR` FOREIGN KEY (`COLLECTOR_ID`) REFERENCES `COLLECTOR` (`COLLECTOR_ID`),
  CONSTRAINT `FK_A_GENERAL_TIME` FOREIGN KEY (`GENERAL_TIME_ID`) REFERENCES `GENERAL_TIME` (`GENERAL_TIME_ID`),
  CONSTRAINT `FK_A_SITE` FOREIGN KEY (`SITE_ID`) REFERENCES `SITE` (`SITE_ID`),
  CONSTRAINT `FK_A_GEO_LOCATION` FOREIGN KEY (`GEO_LOCATION_ID`) REFERENCES `GEO_LOCATION` (`GEO_LOCATION_ID`),
  CONSTRAINT `FK_A_CORPUS` FOREIGN KEY (`CORPUS_ID`) REFERENCES `CORPUS` (`CORPUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `LINE` (
  `LINE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ANNOTATION` longtext,
  `ANNOTATION_ID` varchar(50) NOT NULL,
  `END_TIME` bigint(20) DEFAULT NULL,
  `INTERVENE_TIME` bigint(20) DEFAULT NULL,
  `NUM_WORDS` int(11) DEFAULT NULL,
  `PARTICIPANT` varchar(50) DEFAULT NULL,
  `UTTERANCE` longtext,
  `START_TIME` bigint(20) DEFAULT NULL,
  `SYS_DATE` datetime DEFAULT NULL,
  `TURN_TIME` bigint(20) DEFAULT NULL,
  `ARTIFACT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`LINE_ID`),
  UNIQUE KEY `ARTIFACT_ID` (`ARTIFACT_ID`,`ANNOTATION_ID`),
  KEY `FK_U_ARTIFACT` (`ARTIFACT_ID`),
  CONSTRAINT `FK_U_ARTIFACT` FOREIGN KEY (`ARTIFACT_ID`) REFERENCES `ARTIFACT` (`ARTIFACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENCOUNTER` (
  `ENCOUNTER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BYSTANDERS` binary(1) DEFAULT NULL,
  `COLLECTION_DATE` datetime DEFAULT NULL,
  `COMMENTS` longtext,
  `DURATION` int(11) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `NUM_PARTICIPANTS` int(11) DEFAULT NULL,
  `PART_FAMIL` binary(1) DEFAULT NULL,
  `FIRST_ENCOUNTER` binary(1) DEFAULT NULL,
  `SYS_DATE` datetime DEFAULT NULL,
  `COLLECTOR_ID` bigint(20) DEFAULT NULL,
  `CORPUS_ID` bigint(20) DEFAULT NULL,
  `DOMAIN_ID` bigint(20) NOT NULL,
  `ENC_QUALITY_ID` bigint(20) DEFAULT NULL,
  `ENC_REASON_ID` bigint(20) DEFAULT NULL,
  `GENERAL_TIME_ID` bigint(20) DEFAULT NULL,
  `GEO_LOCATION_ID` bigint(20) DEFAULT NULL,
  `SITE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ENCOUNTER_ID`),
  UNIQUE KEY `NAME` (`NAME`),
  KEY `FK_ENC_COLLECTOR` (`COLLECTOR_ID`),
  KEY `FK_ENC_QUALITY` (`ENC_QUALITY_ID`),
  KEY `FK_ENC_DOMAIN` (`DOMAIN_ID`),
  KEY `FK_ENC_SITE` (`SITE_ID`),
  KEY `FK_ENC_REASON` (`ENC_REASON_ID`),
  KEY `FK_ENC_GEO_LOCATION` (`GEO_LOCATION_ID`),
  KEY `FK_ENC_GENERAL_TIME` (`GENERAL_TIME_ID`),
  KEY `FK_ENC_CORPUS` (`CORPUS_ID`),
  CONSTRAINT `FK_ENC_CORPUS` FOREIGN KEY (`CORPUS_ID`) REFERENCES `CORPUS` (`CORPUS_ID`),
  CONSTRAINT `FK_ENC_QUALITY` FOREIGN KEY (`ENC_QUALITY_ID`) REFERENCES `ENC_QUALITY` (`ENC_QUALITY_ID`),
  CONSTRAINT `FK_ENC_REASON` FOREIGN KEY (`ENC_REASON_ID`) REFERENCES `ENC_REASON` (`ENC_REASON_ID`),
  CONSTRAINT `FK_ENC_COLLECTOR` FOREIGN KEY (`COLLECTOR_ID`) REFERENCES `COLLECTOR` (`COLLECTOR_ID`),
  CONSTRAINT `FK_ENC_GENERAL_TIME` FOREIGN KEY (`GENERAL_TIME_ID`) REFERENCES `GENERAL_TIME` (`GENERAL_TIME_ID`),
  CONSTRAINT `FK_ENC_DOMAIN` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `DOMAIN` (`DOMAIN_ID`),
  CONSTRAINT `FK_ENC_SITE` FOREIGN KEY (`SITE_ID`) REFERENCES `SITE` (`SITE_ID`),
  CONSTRAINT `FK_ENC_GEO_LOCATION` FOREIGN KEY (`GEO_LOCATION_ID`) REFERENCES `geo_location` (`GEO_LOCATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `PARTICIPANT` (
  `PARTICIPANT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AGE` int(11) DEFAULT NULL,
  `CODE_NAME` varchar(45) NOT NULL,
  `COMMENTS` longtext,
  `SOCIOMETRIC_BADGE` varchar(100) DEFAULT NULL,
  `SYS_DATE` datetime DEFAULT NULL,
  `TIME_IN_COUNTRY` int(11) DEFAULT NULL,
  `ENCOUNTER_ID` bigint(20) NOT NULL,
  `ETHNICITY_ID` bigint(20) DEFAULT NULL,
  `GENDER_ID` bigint(20) DEFAULT NULL,
  `GEO_LOCATION_ID` bigint(20) DEFAULT NULL,
  `PARTICIPANT_TYPE_ID` bigint(20) NOT NULL,
  `RANK_ID` bigint(20) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PARTICIPANT_ID`),
  UNIQUE KEY `ENCOUNTER_ID` (`ENCOUNTER_ID`,`CODE_NAME`),
  KEY `FK_PT_GENDER` (`GENDER_ID`),
  KEY `FK_PT_ROLE` (`ROLE_ID`),
  KEY `FK_PT_RANK` (`RANK_ID`),
  KEY `FK_PT_ETHNICITY` (`ETHNICITY_ID`),
  KEY `FK_PT_GEO_LOCATION` (`GEO_LOCATION_ID`),
  KEY `FK_PT_ENCOUNTER` (`ENCOUNTER_ID`),
  KEY `FK_PARTICIPANT_TYPE` (`PARTICIPANT_TYPE_ID`),
  CONSTRAINT `FK_PARTICIPANT_TYPE` FOREIGN KEY (`PARTICIPANT_TYPE_ID`) REFERENCES `PARTICIPANT_TYPE` (`PARTICIPANT_TYPE_ID`),
  CONSTRAINT `FK_PT_GEO_LOCATION` FOREIGN KEY (`GEO_LOCATION_ID`) REFERENCES `GEO_LOCATION` (`GEO_LOCATION_ID`),
  CONSTRAINT `FK_PT_RANK` FOREIGN KEY (`RANK_ID`) REFERENCES `RANK` (`RANK_ID`),
  CONSTRAINT `FK_PT_ETHNICITY` FOREIGN KEY (`ETHNICITY_ID`) REFERENCES `ETHNICITY` (`ETHNICITY_ID`),
  CONSTRAINT `FK_PT_ENCOUNTER` FOREIGN KEY (`ENCOUNTER_ID`) REFERENCES `ENCOUNTER` (`ENCOUNTER_ID`),
  CONSTRAINT `FK_PT_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_PT_GENDER` FOREIGN KEY (`GENDER_ID`) REFERENCES `GENDER` (`GENDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `INTERVIEW_X_ARTIFACT` (
  `INTERVIEW_INTERVIEW_ID` bigint(20) NOT NULL,
  `ARTIFACT_ARTIFACT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`INTERVIEW_INTERVIEW_ID`,`ARTIFACT_ARTIFACT_ID`),
  KEY `FK_INTERVIEW` (`INTERVIEW_INTERVIEW_ID`),
  KEY `FK_ARTIFACT` (`ARTIFACT_ARTIFACT_ID`),
  CONSTRAINT `FK_IXA_ARTIFACT` FOREIGN KEY (`ARTIFACT_ARTIFACT_ID`) REFERENCES `ARTIFACT` (`ARTIFACT_ID`),
  CONSTRAINT `FK_IXA_INTERVIEW` FOREIGN KEY (`INTERVIEW_INTERVIEW_ID`) REFERENCES `INTERVIEW` (`INTERVIEW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `INTERVIEW_X_ENCOUNTER` (
  `ENCOUNTER_ENCOUNTER_ID` bigint(20) NOT NULL,
  `INTERVIEW_INTERVIEW_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ENCOUNTER_ENCOUNTER_ID`,`INTERVIEW_INTERVIEW_ID`),
  KEY `FK_INTERVIEW` (`INTERVIEW_INTERVIEW_ID`),
  KEY `FK_ENCOUNTER` (`ENCOUNTER_ENCOUNTER_ID`),
  CONSTRAINT `FK_IXE_ENCOUNTER` FOREIGN KEY (`ENCOUNTER_ENCOUNTER_ID`) REFERENCES `ENCOUNTER` (`ENCOUNTER_ID`),
  CONSTRAINT `FK_IXE_INTERVIEW` FOREIGN KEY (`INTERVIEW_INTERVIEW_ID`) REFERENCES `INTERVIEW` (`INTERVIEW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `PARTICIPANT_X_LANGUAGE` (
  `PARTICIPANT_PARTICIPANT_ID` bigint(20) NOT NULL,
  `LANGUAGE_LANGUAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PARTICIPANT_PARTICIPANT_ID`,`LANGUAGE_LANGUAGE_ID`),
  KEY `FK_PARTICIPANT` (`PARTICIPANT_PARTICIPANT_ID`),
  KEY `FK_LANGUAGE` (`LANGUAGE_LANGUAGE_ID`),
  CONSTRAINT `FK_PXL_LANGUAGE` FOREIGN KEY (`LANGUAGE_LANGUAGE_ID`) REFERENCES `LANGUAGE` (`LANGUAGE_ID`),
  CONSTRAINT `FK_PXL_PARTICIPANT` FOREIGN KEY (`PARTICIPANT_PARTICIPANT_ID`) REFERENCES `PARTICIPANT` (`PARTICIPANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENCOUNTER_X_ARTIFACT` (
  `ENCOUNTER_ENCOUNTER_ID` bigint(20) NOT NULL,
  `ARTIFACT_ARTIFACT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ENCOUNTER_ENCOUNTER_ID`,`ARTIFACT_ARTIFACT_ID`),
  KEY `FK_ENCOUNTER` (`ENCOUNTER_ENCOUNTER_ID`),
  KEY `FK_ARTIFACT` (`ARTIFACT_ARTIFACT_ID`),
  CONSTRAINT `FK_EXA_ARTIFACT` FOREIGN KEY (`ARTIFACT_ARTIFACT_ID`) REFERENCES `ARTIFACT` (`ARTIFACT_ID`),
  CONSTRAINT `FK_EXA_ENCOUNTER` FOREIGN KEY (`ENCOUNTER_ENCOUNTER_ID`) REFERENCES `ENCOUNTER` (`ENCOUNTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENCOUNTER_X_LANGUAGE` (
  `ENCOUNTER_ENCOUNTER_ID` bigint(20) NOT NULL,
  `LANGUAGE_LANGUAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ENCOUNTER_ENCOUNTER_ID`,`LANGUAGE_LANGUAGE_ID`),
  KEY `FK_ENCOUNTER` (`ENCOUNTER_ENCOUNTER_ID`),
  KEY `FK_LANGUAGE` (`LANGUAGE_LANGUAGE_ID`),
  CONSTRAINT `FK_EXL_LANGUAGE` FOREIGN KEY (`LANGUAGE_LANGUAGE_ID`) REFERENCES `LANGUAGE` (`LANGUAGE_ID`),
  CONSTRAINT `FK_EXL_ENCOUNTER` FOREIGN KEY (`ENCOUNTER_ENCOUNTER_ID`) REFERENCES `ENCOUNTER` (`ENCOUNTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;


CREATE TABLE `USER_ROLE` (
  `USER_ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `enumValue` int(11) DEFAULT NULL,
  `ROLE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  UNIQUE KEY `ROLE` (`ROLE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
;
CREATE TABLE `USER` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PASSWORD` tinyblob NOT NULL,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`),
  KEY `FK_USER_ROLE` (`USER_ROLE_ID`),
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `USER_ROLE` (`USER_ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;



