<?xml version='1.0' encoding='UTF-8'?>
<!--
 * National Training and Education Resource (NTER)
 * Copyright (C) 2012  SRI International
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
-->
<wsdl:definitions name="Blacklist-api"
    targetNamespace="http://nterlearning.org/xml/nter-registry/blacklist-api_0.1.0.wsdl"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:tns="http://nterlearning.org/xml/nter-registry/blacklist-api_0.1.0.wsdl"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:face="http://nterlearning.org/xml/nter-registry/blacklist-interface_0.1.0.wsdl"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
>

    <wsdl:import
            namespace="http://nterlearning.org/xml/nter-registry/blacklist-interface_0.1.0.wsdl"
            location="blacklist-interface_0.1.0.wsdl"/>

    <wsdl:binding
            name="BlacklistSoapBinding"
            type="face:BlacklistInterface">

        <soap12:binding style="document"
                        transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="addBlacklistItem">
            <wsp:PolicyReference URI="#securityPolicy"/>
            <soap12:operation soapAction="urn:addBlacklistItem"
                              style="document"/>
            <wsdl:input name="addBlacklistItem">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="addBlacklistItemResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="updateBlacklistItem">
            <wsp:PolicyReference URI="#securityPolicy"/>
            <soap12:operation soapAction="urn:updateBlacklistItem"
                              style="document"/>
            <wsdl:input name="updateBlacklistItem">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="updateBlacklistItemResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="removeBlacklistItem">
            <wsp:PolicyReference URI="#securityPolicy"/>
            <soap12:operation soapAction="urn:removeBlacklistItem"
                              style="document"/>
            <wsdl:input name="removeBlacklistItem">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="removeBlacklistItemResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="getBlacklistStatus">
            <soap12:operation soapAction="urn:getBlacklistStatus"
                              style="document"/>
            <wsdl:input name="getBlacklistStatus">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getBlacklistStatusResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="setBlacklistDefault">
            <wsp:PolicyReference URI="#securityPolicy"/>
            <soap12:operation soapAction="urn:setBlacklistDefault"
                              style="document"/>
            <wsdl:input name="setBlacklistDefault">
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="setBlacklistDefaultResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>

    <wsdl:service name="Blacklist-api">
        <wsdl:port binding="tns:BlacklistSoapBinding"
                   name="BlacklistSoap12EndPoint">
            <soap12:address
                    location="/Blacklist-api"/>
        </wsdl:port>
    </wsdl:service>

    <wsp:Policy wsu:Id="securityPolicy">
        <sp:SupportingTokens>
            <wsp:Policy>
                <sp:UsernameToken/>
            </wsp:Policy>
        </sp:SupportingTokens>
    </wsp:Policy>

</wsdl:definitions>