CREATE TABLE `ACTIVE_STATUS` (
  `ACTIVE_STATUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(50) NOT NULL,
  PRIMARY KEY (`ACTIVE_STATUS_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
;
CREATE TABLE `BLACK_LIST` (
  `BLACK_LIST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INSTITUTION` varchar(100) NOT NULL,
  `SERVICE` varchar(100) DEFAULT NULL,
  `ACTIVE_STATUS_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`BLACK_LIST_ID`),
  UNIQUE KEY `INSTITUTION` (`INSTITUTION`,`SERVICE`),
  KEY `FKBD07DCFE49AD62E7` (`ACTIVE_STATUS_ID`),
  CONSTRAINT `FKBD07DCFE49AD62E7` FOREIGN KEY (`ACTIVE_STATUS_ID`) REFERENCES `ACTIVE_STATUS` (`ACTIVE_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
