CREATE DATABASE ENTITLEMENT_DB;

USE ENTITLEMENT_DB
;
CREATE TABLE `ACTION` (
  `ACTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(50) NOT NULL,
  PRIMARY KEY (`ACTION_ID`),
  UNIQUE KEY `VALUE` (`VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
CREATE TABLE `ENTITLEMENT_POLICY` (
  `POLICY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REALM` varchar(255) DEFAULT NULL,
  `RESOURCE` varchar(255) DEFAULT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `ACTION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`POLICY_ID`),
  UNIQUE KEY `SUBJECT` (`SUBJECT`,`REALM`,`RESOURCE`),
  KEY `FK_ACTION` (`ACTION_ID`),
  CONSTRAINT `FK_ACTION` FOREIGN KEY (`ACTION_ID`) REFERENCES `ACTION` (`ACTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
