use COMMERCE_DB;

ALTER TABLE PAYMENT_TRANSACTION ADD REASON_CODE VARCHAR(255);

ALTER TABLE PAYMENT_CONFIG ADD API_USER VARCHAR(255);

ALTER TABLE PAYMENT_CONFIG ADD API_PASSWORD VARCHAR(255);

ALTER TABLE PAYMENT_CONFIG ADD API_SIGNATURE VARCHAR(255);

ALTER TABLE PAYMENT_CONFIG ADD SELLER_EMAIL VARCHAR(255);

ALTER TABLE PAYMENT_TRANSACTION MODIFY COLUMN PAYMENT_DATE DATETIME;

ALTER TABLE PAYMENT_TRANSACTION MODIFY COLUMN SYS_DATE DATETIME;
